sonar.projectKey=sirosfoundation_go-wmp
sonar.organization=sirosfoundation

sonar.sources=.
sonar.exclusions=cmd/**,examples/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.txt
sonar.coverage.exclusions=cmd/**,examples/**
